### ISSUE TITLE
Messenger Settings API endpoint(s) does not work

### ISSUE THREAD

**Issue by burningtree** [amio-io/amio#21]
**Summary:**
It's not possible to get (1) or update (2) Messenger settings, because Amio API returns "Method Not Allowed" or "Internal Error".

## 1. Get settings
`GET https://api.amio.io/v1/channels/6488357877962263032/settings`

Result:
```json
{
  "timestamp": "2019-01-11T17:05:06.620Z",
  "status": {
    "code": 500,
    "message": "Internal Server Error"
  },
  "errors": [
    {
      "message": "Internal Server Error"
    }
  ]
}
```

## 2. Update settings

`POST https://api.amio.io/v1/channels/6488357877962263032/settings`
```json
{ 
  "get_started_button": {
    "payload": "xxx"
  }
}
```

Returns:
`HTTP Error 405`
```json
{
  "timestamp": "2019-01-11T16:59:31.521Z",
  "status": {
    "code": 405,
    "message": "Method Not Allowed"
  },
  "errors": [
    {
      "message": "Method Not Allowed"
    }
  ]
}
```

**Comment by zatziky** [comment]
Hey @burningtree, I have 2 good news for you and 1 not so good. :)

# Ad 1. Get Settings
I've checked the logs of your error and the good news is that **GET and UPDATE are working!** It's working for me now and I saw that at least first 2 responses you received on `GET /settings` were successful for you too.

What happened is that your FB page exceeded **Facebook rate limits**. We received this error from Facebook:
```
{
  "error": {
    "code": 613,
    "message": "(#613) Calls to this api have exceeded the rate limit.",
    "type": "OAuthException",
    "fbtrace_id": "CPeHRfm2Q3f"
  }
}
```

We usually translate every error to our [API error](https://docs.amio.io/v1.0/reference#errors). Since we didn't cover the **code 613** yet, we translated mistakenly the error as `500:Internal Server Error`. We will add it now.

The biggest issue is with Facebook, we've reported them several times that the **FB Page Rate Limits** is too low. So, we will try again. (That's the one bad news. :) I let you know as soon as we will add it.

# Ad 2. Update settings
You've used an unsupported method (HTTP verb) `POST`. The [settings endpoint](https://docs.amio.io/v1.0/reference#facebook-messenger-settings) supports only `GET` and `PATCH`. You probably wanted to use `PATCH` in order to update the settings.

We've chosen `PATCH` instead of `POST` since there's always a settings object and you're just making partial updates to it. That's exactly why `PATCH` exists.

**Comment by zatziky** [comment]
Hi @burningtree , 

we have correct the error and now it tells you this:
```
{
    "timestamp": "2019-01-13T09:17:20.996Z",
    "status": {
        "code": 400,
        "message": "Bad Request"
    },
    "errors": [
        {
            "message": "Error while requesting Facebook api. You have exceeded the Facebook API rate limits for this FB Page settings. (Amio has different API limits and we cannot influence the ones from Facebook) Facebook doesn't specify when you can start making the calls again. According to our observation, you can come back in several minutes and invoke some more calls again."
        }
    ]
}
```

I hope it makes sense.
